-- 코드를 입력하세요
SELECT
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM
    AUTHOR AS A
JOIN
    BOOK AS B ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN
    BOOK_SALES AS BS ON BS.BOOK_ID = B.BOOK_ID
WHERE
    BS.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
    