-- 코드를 작성해주세요
SELECT
    II.ITEM_ID AS ITEM_ID,
    II.ITEM_NAME AS ITEM_NAME,
    II.RARITY AS RARITY
FROM ITEM_INFO AS II
WHERE 
    ITEM_ID NOT IN(
        SELECT PARENT_ITEM_ID
        FROM ITEM_TREE
        WHERE NOT ISNULL(PARENT_ITEM_ID))
ORDER BY ITEM_ID DESC;