-- 코드를 입력하세요
SELECT 
    AO.ANIMAL_ID AS ANIMAL_ID,
    AO.NAME AS NAME
FROM    
    ANIMAL_OUTS AS AO
INNER JOIN ANIMAL_INS AS AI
ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY DATEDIFF(AO.DATETIME,AI.DATETIME) DESC
LIMIT 2;