-- 코드를 입력하세요
SELECT
    UU.USER_ID AS USER_ID,
    UU.NICKNAME AS NICKNAME,
    CONCAT(UU.CITY,' ',UU.STREET_ADDRESS1,' ',UU.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTRING(UU.TLNO,1,3),'-',
          SUBSTRING(UU.TLNO,4,4),'-',
          SUBSTRING(UU.TLNO,8)) AS 전화번호
FROM USED_GOODS_USER AS UU
INNER JOIN USED_GOODS_BOARD AS UB ON UU.USER_ID = UB.WRITER_ID
GROUP BY UU.USER_ID
HAVING COUNT(UU.USER_ID) >= 3
ORDER BY UU.USER_ID DESC