-- 코드를 입력하세요
SELECT
    AI.ANIMAL_ID AS ANIMAL_ID,
    AI.ANIMAL_TYPE AS ANIMAL_TYPE,
    AI.NAME AS NAME
FROM
    ANIMAL_INS AS AI
JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE
    AI.SEX_UPON_INTAKE != AO.SEX_UPON_OUTCOME;