-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    UI.GENDER AS GENDER,
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM
    ONLINE_SALE AS OS
JOIN
    USER_INFO AS UI ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER is not NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;