-- 코드를 작성해주세요
SELECT
    COUNT(fn.FISH_TYPE) AS FISH_COUNT,
    fn.FISH_NAME
FROM
    FISH_NAME_INFO fn
JOIN FISH_INFO f ON fn.FISH_TYPE = f.FISH_TYPE
GROUP BY
    fn.FISH_NAME
ORDER BY
    FISH_COUNT DESC;