-- 코드를 입력하세요
SELECT
    UU.USER_ID AS USER_ID,
    UU.NICKNAME AS NICKNAME,
    SUM(UB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_USER AS UU
INNER JOIN 
    USED_GOODS_BOARD AS UB
ON UU.USER_ID = UB.WRITER_ID
WHERE UB.STATUS='DONE'
GROUP BY
    UU.USER_ID
HAVING
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES ASC;
