-- 코드를 입력하세요
SELECT FH.FLAVOR AS FLAVOR FROM FIRST_HALF AS FH
JOIN ICECREAM_INFO AS I ON FH.FLAVOR = I.FLAVOR
WHERE FH.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FH.TOTAL_ORDER DESC;