-- 코드를 작성해주세요
SELECT 
    SUM(HG.SCORE) AS SCORE,
    HE.EMP_NO AS EMP_NO,
    HE.EMP_NAME AS EMP_NAME,
    HE.POSITION AS POSITION,
    HE.EMAIL AS EMAIL
FROM HR_EMPLOYEES AS HE
INNER JOIN HR_DEPARTMENT AS HD ON HD.DEPT_ID = HE.DEPT_ID
INNER JOIN HR_GRADE AS HG ON HG.EMP_NO = HE.EMP_NO
GROUP BY HE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;