-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/',UB.BOARD_ID,'/',UF.FILE_ID,UF.FILE_NAME,UF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS UF
INNER JOIN USED_GOODS_BOARD AS UB
ON UF.BOARD_ID=UB.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;
