-- 코드를 입력하세요
SELECT
    B.CATEGORY AS CATEGORY,
    SUM(BS.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
INNER JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE
    MONTH(BS.SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;